name: otpts

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://registry.npmjs.org/
    - name: Lint, test and build
      run: |
        yarn install --frozen-lockfile
        yarn lint
        yarn test
        yarn build
      env:
        CI: true
    - name: Publish
      run: yarn --silent run scripts/canPublish && npm publish || echo "No need to publish"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
